export const FRASES = [
    'NO QUIERO ANIQUILAR A NADIE, ODIO A LOS ABUSIVOS, SEAN DE DONDE SEAN.',
    'ANTES DE EMPEZAR, ¿ALGUIEN PREFIERE RETIRARSE?',
    'CUANDO NO TENÍA NADA, TENÍA A BUCKY.',
    'EL PRECIO DE LA LIBERTAD ES ALTO, SIEMPRE LO HA SIDO Y ESTOY DISPUESTO A PAGAR EL PRECIO, SI DEBO PELEAR SÓLO QUE ASÍ SEA.',
    'ÉSTA ES LA PELEA DE NUESTRAS VIDAS, Y VAMOS A GANAR, HAREMOS LO QUE SEA.',
    'HARÍA ESTO TODO EL DÍA.',
    'HACE CINCO AÑOS PERDIMOS TODOS, PERDIMOS AMIGOS, PERDIMOS FAMILIA Y UNA PARTE DE NOSOTROS.',
    'SÓLO HAY UN DIOS PARA MÍ, Y JAMÁS SE VESTIRÍA ASÍ.',
    'A TU IZQUIERDA.',
    'YO SÍ, ES QUE SÍ ENTENDI LA REFERENCIA',
    'YO SÉ QUE SÍ, PORQUE NO SÉ LO QUÉ VOY A HACER SI NO'
];
