export const FRASES = [
    'HONRA A LAS VIUDAS QUE EN VERDAD LO SON.', // 1 TIMOTEO 5:3
    '!MIRAD CUÁN BUENO Y CUÁN DELICIOSO ES HABITAR LOS HERMANOS JUNTOS EN ARMONÍA!', // SALMO 133:1
    'PORQUE DONDE ESTÁN DOS O TRES CONGREGADOS EN MI NOMBRE, ALLÍ ESTOY YO EN MEDIO DE ELLOS.', // MATEO 18:20
    'FINALMENTE, SED TODOS DE UN MISMO SENTIR, COMPASIVOS, AMÁNDOOS FRATERNALMENTE, MISERICORDIOSOS, AMIGABLES.', // 1 PEDRO 3:8
    'SOLÍCITOS EN GUARDAR LA UNIDAD DEL ESPÍRITU EN EL VÍNCULO DE LA PAZ.', // EFESIOS 4:3
    'AMADOS, SI DIOS NOS HA AMADO ASÍ, DEBEMOS TAMBIÉN NOSOTROS AMARNOS UNOS A OTROS.', // 1 JUAN 4:11
    'Y SOBRE TODAS ESTAS COSAS VESTÍOS DE AMOR, QUE ES EL VÍNCULO PERFECTO.', // COLOSENSES 3:14
    'RECIBID AL DÉBIL EN LA FE, PERO NO PARA CONTENDER SOBRE OPINIONES.', // ROMANOS 14:1
    '¿NO SABÉIS QUE SOIS TEMPLO DE DIOS, Y QUE EL ESPÍRITU DE DIOS MORA EN VOSOTROS?', // 1 CORINTIOS 3:16
    'ASÍ QUE PEDRO ESTABA CUSTODIADO EN LA CÁRCEL; PERO LA IGLESIA HACÍA SIN CESAR ORACIÓN A DIOS POR ÉL.', // HECHOS 12:5
    'UNÁNIMES ENTRE VOSOTROS; NO ALTIVOS, SINO ASOCIÁNDOOS CON LOS HUMILDES. NO SEÁIS SABIOS EN VUESTRA PROPIA OPINIÓN.', // ROMANOS 12:16
    'PERO EL DIOS DE LA PACIENCIA Y DE LA CONSOLACIÓN OS DÉ ENTRE VOSOTROS UN MISMO SENTIR SEGÚN CRISTO JESÚS.', // ROMANOS 15:5
    'Y LA MULTITUD DE LOS QUE HABÍAN CREÍDO ERA DE UN CORAZÓN Y UN ALMA; Y NINGUNO DECÍA SER SUYO PROPIO NADA DE LO QUE POSEÍA, SINO QUE TENÍAN TODAS LAS COSAS EN COMÚN.', // HECHOS 4:32
    'PERO SI ANDAMOS EN LUZ, COMO ÉL ESTÁ EN LUZ, TENEMOS COMUNIÓN UNOS CON OTROS, Y LA SANGRE DE JESUCRISTO SU HIJO NOS LIMPIA DE TODO PECADO.', // 1 JUAN 1:7
    'YA NO HAY JUDÍO NI GRIEGO; NO HAY ESCLAVO NI LIBRE; NO HAY VARÓN NI MUJER; PORQUE TODOS VOSOTROS SOIS UNO EN CRISTO JESÚS.', // GÁLATAS 3:28
    'MAS OS RUEGO, HERMANOS, QUE OS FIJÉIS EN LOS QUE CAUSAN DIVISIONES Y TROPIEZOS EN CONTRA DE LA DOCTRINA QUE VOSOTROS HABÉIS APRENDIDO, Y QUE OS APARTÉIS DE ELLOS.', // ROMANOS 16:17
    'DE CIERTO, DE CIERTO OS DIGO: EL QUE RECIBE AL QUE YO ENVIARE, ME RECIBE A MÍ; Y EL QUE ME RECIBE A MÍ, RECIBE AL QUE ME ENVIÓ.', // JUAN 13:20
    'TODOS ÉSTOS PERSEVERABAN UNÁNIMES EN ORACIÓN Y RUEGO, CON LAS MUJERES, Y CON MARÍA LA MADRE DE JESÚS, Y CON SUS HERMANOS.', // HECHOS 1:14
    'PORQUE POR UN SOLO ESPÍRITU FUIMOS TODOS BAUTIZADOS EN UN CUERPO, SEAN JUDÍOS O GRIEGOS, SEAN ESCLAVOS O LIBRES; Y A TODOS SE NOS DIO A BEBER DE UN MISMO ESPÍRITU.', // 1 CORINTIOS 12:13
    'Y PERSEVERABAN EN LA DOCTRINA DE LOS APÓSTOLES, EN LA COMUNIÓN UNOS CON OTROS, EN EL PARTIMIENTO DEL PAN Y EN LAS ORACIONES.', // HECHOS 2:42
    'PORQUE ASÍ COMO EL CUERPO ES UNO, Y TIENE MUCHOS MIEMBROS, PERO TODOS LOS MIEMBROS DEL CUERPO, SIENDO MUCHOS, SON UN SOLO CUERPO, ASÍ TAMBIÉN CRISTO.', // 1 CORINTIOS 12:12
    'SI ALGUNO DESTRUYERE EL TEMPLO DE DIOS, DIOS LE DESTRUIRÁ A ÉL; PORQUE EL TEMPLO DE DIOS, EL CUAL SOIS VOSOTROS, SANTO ES.', // 1 CORINTIOS 3:17
    'Y YO TAMBIÉN TE DIGO, QUE TÚ ERES PEDRO, Y SOBRE ESTA ROCA EDIFICARÉ MI IGLESIA; Y LAS PUERTAS DEL HADES NO PREVALECERÁN CONTRA ELLA.', // MATEO 16:18
    'Y CONSIDERÉMONOS UNOS A OTROS PARA ESTIMULARNOS AL AMOR Y A LAS BUENAS OBRAS; NO DEJANDO DE CONGREGARNOS, COMO ALGUNOS TIENEN POR COSTUMBRE, SINO EXHORTÁNDONOS; Y TANTO MÁS, CUANTO VEIS QUE AQUEL DÍA SE ACERCA.', // HEBREOS 10:24-25"
    'PORQUE DE LA MANERA QUE EN UN CUERPO TENEMOS MUCHOS MIEMBROS, PERO NO TODOS LOS MIEMBROS TIENEN LA MISMA FUNCIÓN, ASÍ NOSOTROS, SIENDO MUCHOS, SOMOS UN CUERPO EN CRISTO, Y TODOS MIEMBROS LOS UNOS DE LOS OTROS.', // ROMANOS 12:4-5
    'OS RUEGO, PUES, HERMANOS, POR EL NOMBRE DE NUESTRO SEÑOR JESUCRISTO, QUE HABLÉIS TODOS UNA MISMA COSA, Y QUE NO HAYA ENTRE VOSOTROS DIVISIONES, SINO QUE ESTÉIS PERFECTAMENTE UNIDOS EN UNA MISMA MENTE Y EN UN MISMO PARECER.', // 1 CORINTIOS 1:10
    'Y PERSEVERANDO UNÁNIMES CADA DÍA EN EL TEMPLO, Y PARTIENDO EL PAN EN LAS CASAS, COMÍAN JUNTOS CON ALEGRÍA Y SENCILLEZ DE CORAZÓN, ALABANDO A DIOS, Y TENIENDO FAVOR CON TODO EL PUEBLO. Y EL SEÑOR AÑADÍA CADA DÍA A LA IGLESIA LOS QUE HABÍAN DE SER SALVOS.' // HECHOS 2:46-47
];
