export const FRASES = [
  '¿QUIÉN SOY YO PARA QUE VAYA A FARAÓN Y SAQUÉ DE EGIPTO A LOS HIJOS DE ISRAEL?',
  'BENDITO POR JEHOVÁ MI DIOS SEA SEM, Y SEA CANAÁN SU SIERVO',
  'SI ME ATAREN FUERTEMENTE CON CUERDAS NUEVAS QUE NO SE HAYAN USADO, YO ME DEBILITARÉ, Y SERÉ COMO CUALQUIERA DE LOS HOMBRES',
  'OH REY, SI HE HALLADO GRACIA EN TUS OJOS, Y SI AL REY PLACE, SÉAME DADA MI VIDA POR MI PETICIÓN, Y MI PUEBLO POR MI DEMANDA',
  'LAS AGUAS ME RODEARON HASTA EL ALMA, RODEOME EL ABISMO; EL ALGA SE ENREDÓ A MI CABEZA',
  'Y SI MAL OS PARECE SERVIR A JEHOVÁ, ESCOGEOS HOY A QUIÉN SIRVÁIS; SI A LOS DIOSES A QUIENES SIRVIERON VUESTROS PADRES, CUANDO ESTUVIERON AL OTRO LADO DEL RÍO, O A LOS DIOSES DE LOS AMORREOS EN CUYA TIERRA HABITÁIS; PERO YO Y MI CASA SERVIREMOS A JEHOVÁ',
  'PORQUE PARA MÍ EL VIVIR ES CRISTO, Y EL MORIR ES GANANCIA',
  'Y ÉL LES DIJO: OÍD AHORA ESTE SUEÑO QUE HE SOÑADO: 7 HE AQUÍ QUE ATÁBAMOS MANOJOS EN MEDIO DEL CAMPO, Y HE AQUÍ QUE MI MANOJO SE LEVANTABA Y ESTABA DERECHO, Y QUE VUESTROS MANOJOS ESTABAN ALREDEDOR Y SE INCLINABAN AL MÍO',
  'MAS AHORA QUE HA MUERTO, ¿PARA QUÉ HE DE AYUNAR? ¿PODRÉ YO HACERLE VOLVER? YO VOY A ÉL, MAS ÉL NO VOLVERÁ A MÍ',
  'EL MISTERIO QUE EL REY DEMANDA, NI SABIOS, NI ASTRÓLOGOS, NI MAGOS NI ADIVINOS LO PUEDEN REVELAR AL REY',
  'LO QUE ERA DESDE EL PRINCIPIO, LO QUE HEMOS OÍDO, LO QUE HEMOS VISTO CON NUESTROS OJOS, LO QUE HEMOS CONTEMPLADO, Y PALPARON NUESTRAS MANOS TOCANTE AL VERBO DE VIDA'
];
