export const FRASES = [
    'BENDICE, ALMA MÍA, A JEHOVÁ, Y BENDIGA TODO MI SER SU SANTO NOMBRE. BENDICE, ALMA MÍA, A JEHOVÁ, Y NO OLVIDES NINGUNO DE SUS BENEFICIOS.',
    'NUNCA SE APARTARÁ DE TU BOCA ESTE LIBRO DE LA LEY, SINO QUE DE DÍA Y DE NOCHE MEDITARÁS EN ÉL, PARA QUE GUARDES Y HAGAS CONFORME A TODO LO QUE EN ÉL ESTÁ ESCRITO; PORQUE ENTONCES HARÁS PROSPERAR TU CAMINO, Y TODO TE SALDRÁ BIEN.',
    'DELÉITATE ASIMISMO EN JEHOVÁ, Y ÉL TE CONCEDERÁ LAS PETICIONES DE TU CORAZÓN.',
    'NO TEMAS, PORQUE YO ESTOY CONTIGO; NO DESMAYES, PORQUE YO SOY TU DIOS QUE TE ESFUERZO; SIEMPRE TE AYUDARÉ, SIEMPRE TE SUSTENTARÉ CON LA DIESTRA DE MI JUSTICIA.',
    'POR NADA ESTÉIS AFANOSOS, SINO SEAN CONOCIDAS VUESTRAS PETICIONES DELANTE DE DIOS EN TODA ORACIÓN Y RUEGO, CON ACCIÓN DE GRACIAS. Y LA PAZ DE DIOS, QUE SOBREPASA TODO ENTENDIMIENTO, GUARDARÁ VUESTROS CORAZONES Y VUESTROS PENSAMIENTOS EN CRISTO JESÚS.',
    'MAS BUSCAD PRIMERAMENTE EL REINO DE DIOS Y SU JUSTICIA, Y TODAS ESTAS COSAS OS SERÁN AÑADIDAS.',
    'JEHOVÁ CUMPLIRÁ SU PROPÓSITO EN MÍ; TU MISERICORDIA, OH JEHOVÁ, ES PARA SIEMPRE; NO DESAMPARES LA OBRA DE TUS MANOS.',
    'HAS AUMENTADO, OH JEHOVÁ DIOS MÍO, TUS MARAVILLAS; Y TUS PENSAMIENTOS PARA CON NOSOTROS, NO ES POSIBLE CONTARLOS ANTE TI. SI YO ANUNCIARE Y HABLARE DE ELLOS, NO PUEDEN SER ENUMERADOS.',
    'TU MUJER SERÁ COMO VID QUE LLEVA FRUTO A LOS LADOS DE TU CASA; TUS HIJOS COMO PLANTAS DE OLIVO ALREDEDOR DE TU MESA.',
    'Y SI MAL OS PARECE SERVIR A JEHOVÁ, ESCOGEOS HOY A QUIÉN SIRVÁIS; SI A LOS DIOSES A QUIENES SIRVIERON VUESTROS PADRES, CUANDO ESTUVIERON AL OTRO LADO DEL RÍO, O A LOS DIOSES DE LOS AMORREOS EN CUYA TIERRA HABITÁIS; PERO YO Y MI CASA SERVIREMOS A JEHOVÁ.',
    'ESTE ES EL DÍA QUE HIZO JEHOVÁ; NOS GOZAREMOS Y ALEGRAREMOS EN ÉL.',
    'MIRA QUE TE MANDO QUE TE ESFUERCES Y SEAS VALIENTE; NO TEMAS NI DESMAYES, PORQUE JEHOVÁ TU DIOS ESTARÁ CONTIGO EN DONDEQUIERA QUE VAYAS.',
];
